[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "velocycle"
authors = [{name = "Alex Lederer", email = "alex.lederer@epfl.ch"}]
dynamic = ["version", "description"]
